### ISSUE TITLE
AttributeError: type object 'PLCA' has no attribute 'F'

### ISSUE THREAD

**Issue by russellb23** [ronw/siplca-segmentation#1]
I am trying to import the code and execute as follows,

>from funcs import PLCA_Weiss
... Code generating the V
... My case V = magnitude

>ss = PLCA_Weiss.PLCA(magn, rank=5, niter=100, printiter=10, convergence_thresh=1e-9
>W, Z, H, norm, recon, logprob = ss.analyze(magn, rank=5, niter=500, printiter=10, convergence_thresh=1e-9)`

My traceback:
`Traceback (most recent call last):
  File "/home/russellb/russell/Python/Audio/musicFeat/libROSA/muFeat/feat_Xt_v2.py", line 56, in <module>
    W, Z, H, norm, recon, logprob = ss.analyze(magn, rank=5, niter=500, printiter=10, convergence_thresh=1e-9)#(magn, rank=5, niter=500, printiter=10, convergence_thresh=1e-9)
  File "/home/russellb/russell/Python/Audio/musicFeat/libROSA/muFeat/funcs/PLCA_Weiss.py", line 249, in analyze
    iW, iZ, iH = params.initialize()
  File "/home/russellb/russell/Python/Audio/musicFeat/libROSA/muFeat/funcs/PLCA_Weiss.py", line 313, in initialize
    W = normalize(np.random.rand(self.F, self.rank), 0)
AttributeError: type object 'PLCA' has no attribute 'F'`

when I try to print F from the class `PLCA`, it prints to the correct number. Could anyone please advise why is this happening or what is that I am doing wrong on this particular thing?

**Comment by russellb23** [comment]
Got that sorted out. It was a problem of python 2 vs python 3 class definition convention. After removing the `object` from `Class PLCA(object):` => `Class PLCA( ):` it worked like a charm.
